spring.application.name=server_backend

# Conexion a Postgres
spring.datasource.url=jdbc:postgresql://db:5432/sincrostock
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
